import { Product } from '../types';
import { PLACEHOLDER_IMAGES, IMAGES } from './imagePlaceholders';

export const MOCK_CATEGORIES = [
  { id: '1', name: 'Boater', label: '', count: '—', image: PLACEHOLDER_IMAGES.product, featured: false },
  { id: '2', name: 'Breton', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '3', name: 'Cartwheel / Picture Hat', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '4', name: 'Cloche', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '5', name: 'Fedora', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '6', name: 'Trilby', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '7', name: 'Bowler / Derby', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '8', name: 'Pork Pie', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '9', name: 'Capeline', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '10', name: 'Sailor Hat', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '11', name: 'Padre / Cappello Romano', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '12', name: 'Pillbox', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '13', name: 'Beret', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '14', name: 'Turban', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '15', name: 'Calotte / Skull Cap', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '16', name: 'Fez / Tarboosh', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '17', name: 'Toque', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '18', name: 'Hood / Cone', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '19', name: 'Fascinator', label: '', count: '—', image: PLACEHOLDER_IMAGES.accessories },
  { id: '20', name: 'Percher', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '21', name: 'Cocktail Hat', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '22', name: 'Halo Hat / Crown', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '23', name: 'Button / Disc', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '24', name: 'Teardrop', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '25', name: 'Juliet Cap', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '26', name: 'Visor', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '27', name: 'Newsboy / Gatsby', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '28', name: 'Ascot / Flat Cap', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
  { id: '29', name: 'Bonnet', label: '', count: '—', image: PLACEHOLDER_IMAGES.bonnet },
  { id: '30', name: 'Bucket Hat', label: '', count: '—', image: PLACEHOLDER_IMAGES.product },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Azure Orchid Hatinator',
    variant: 'Occasion Headwear - Sculpted Bow',
    price: 15.89,
    image: IMAGES[6],
    badge: 'New',
    colors: ['#4f0254', '#4d0353', '#dcdc44'],
    category: 'Hatinators',
  },
  {
    id: '2',
    name: 'Royal Plum Fascinator',
    variant: 'Fascinators - Feather Accent',
    price: 32.0,
    oldPrice: 40.0,
    image: IMAGES[7],
    badge: 'Limited',
    badgeVariant: 'sale',
    colors: ['#351e49', '#e01386', '#b3899e'],
    category: 'Fascinators',
  },
  {
    id: '3',
    name: 'Luxury Satin Sleep Bonnet',
    variant: 'Satin Bonnets - Soft Lining',
    price: 12.5,
    image: IMAGES[8],
    colors: ['#4f0254', '#351e49', '#e01386', '#b3899e'],
    category: 'Bonnets',
  },
  {
    id: '4',
    name: 'Cee Signature Church Hat',
    variant: 'Church Hats - Wide Brim',
    price: 89.0,
    image: IMAGES[9],
    badge: 'Exclusive',
    badgeVariant: 'dark',
    colors: ['#4d0353', '#4f0254', '#f9fc04'],
    category: 'Church Hats',
  },
];
